module.exports = {
  'no-console': 'off',

  'n/callback-return': 'error',
  'n/file-extension-in-import': 'error',
  'n/global-require': 'error',
  'n/handle-callback-err': ['error', '^.*(e|E)rr'],
  'n/no-callback-literal': 'error',
  'n/no-hide-core-modules': 'error',
  'n/no-missing-import': 'off',
  'n/no-mixed-requires': 'error',
  'n/no-new-require': 'error',
  'n/no-path-concat': 'error',
  'n/no-process-env': ['warn', {
    allowedVariables: ['NODE_ENV'],
  }],
  'n/no-sync': 'error',
  'n/no-unpublished-import': 'off',
  'n/no-unsupported-features/es-builtins': 'off',
  'n/no-unsupported-features/node-builtins': 'off',
  'n/prefer-global/buffer': 'error',
  'n/prefer-global/text-decoder': 'error',
  'n/prefer-global/text-encoder': 'error',
  'n/prefer-global/url': 'error',
  'n/prefer-global/url-search-params': 'error',
  'n/prefer-promises/dns': 'error',
  'n/prefer-promises/fs': 'error',
};
