module.exports = {
  'no-console': ['warn', {
    allow: ['warn', 'error'],
  }],

  'n/callback-return': 'error',
  'n/file-extension-in-import': 'error',
  'n/global-require': 'error',
  'n/handle-callback-err': ['error', '^.*(e|E)rr'],
  'n/no-callback-literal': 'error',
  'n/no-hide-core-modules': 'error',
  'n/no-missing-import': 'off',
  'n/no-mixed-requires': 'error',
  'n/no-new-require': 'error',
  'n/no-path-concat': 'error',
  'n/no-process-env': ['warn', {
    allowedVariables: ['NODE_ENV'],
  }],
  'n/no-sync': 'error',
  'n/no-unpublished-import': 'off',
  'n/no-unsupported-features/es-builtins': 'off',
  'n/no-unsupported-features/node-builtins': 'off',
  'n/prefer-global/buffer': ['error', 'never'],
  'n/prefer-global/console': 'error',
  'n/prefer-global/crypto': ['error', 'never'],
  'n/prefer-global/process': ['error', 'never'],
  'n/prefer-global/text-decoder': ['error', 'never'],
  'n/prefer-global/text-encoder': ['error', 'never'],
  'n/prefer-global/timers': ['error', 'never'],
  'n/prefer-global/url': ['error', 'never'],
  'n/prefer-global/url-search-params': ['error', 'never'],
  'n/prefer-promises/dns': 'error',
  'n/prefer-promises/fs': 'error',

  'unicorn/consistent-function-scoping': 'off',
  'unicorn/expiring-todo-comments': 'off',
  'unicorn/filename-case': 'off',
  'unicorn/no-null': 'off',
  'unicorn/numeric-separators-style': 'off',
  'unicorn/prevent-abbreviations': 'off',
};
