module.exports = {
  'array-callback-return': 'error',
  'no-promise-executor-return': 'error',
  'no-self-compare': 'error',
  'no-template-curly-in-string': 'error',
  'no-unused-vars': ['error', {
    varsIgnorePattern: '^_',
    args: 'after-used',
    argsIgnorePattern: '^_',
    caughtErrorsIgnorePattern: '^_',
    destructuredArrayIgnorePattern: '^_',
  }],
  'no-use-before-define': 'error',

  'accessor-pairs': 'error',
  'arrow-body-style': 'error',
  'camelcase': 'error',
  'consistent-return': 'error',
  'curly': 'error',
  'default-case-last': 'error',
  'default-param-last': 'error',
  'dot-notation': 'error',
  'eqeqeq': 'error',
  'guard-for-in': 'error',
  'logical-assignment-operators': 'error',
  'max-nested-callbacks': ['error', 3],
  'new-cap': 'error',
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-caller': 'error',
  'no-console': 'error',
  'no-else-return': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-implicit-coercion': 'error',
  'no-implied-eval': 'error',
  'no-invalid-this': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-loop-func': 'error',
  'no-multi-str': 'error',
  'no-nested-ternary': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-object-constructor': 'error',
  'no-octal-escape': 'error',
  'no-proto': 'error',
  'no-return-assign': 'error',
  'no-script-url': 'error',
  'no-sequences': 'error',
  'no-shadow': ['error', {
    hoist: 'all',
  }],
  'no-throw-literal': 'error',
  'no-undef-init': 'error',
  'no-unneeded-ternary': 'error',
  'no-unused-expressions': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-rename': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'object-shorthand': ['error', 'always', {
    avoidQuotes: true,
  }],
  'one-var': ['error', 'never'],
  'prefer-arrow-callback': 'error',
  'prefer-const': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'radix': 'error',
  'require-await': 'error',
  'strict': ['error', 'never'],
  'yoda': 'error',

  'unicode-bom': 'error',

  '@stylistic/array-bracket-spacing': 'error',
  '@stylistic/arrow-parens': 'error',
  '@stylistic/block-spacing': 'error',
  '@stylistic/brace-style': 'error',
  '@stylistic/comma-dangle': ['error', 'always-multiline'],
  '@stylistic/comma-spacing': 'error',
  '@stylistic/comma-style': 'error',
  '@stylistic/computed-property-spacing': 'error',
  '@stylistic/eol-last': 'error',
  '@stylistic/function-call-spacing': 'error',
  '@stylistic/generator-star-spacing': ['error', 'after'],
  '@stylistic/indent': ['error', 2, {
    SwitchCase: 1,
  }],
  '@stylistic/key-spacing': 'error',
  '@stylistic/keyword-spacing': 'error',
  '@stylistic/lines-between-class-members': ['error', 'always', {
    exceptAfterSingleLine: true,
  }],
  '@stylistic/new-parens': 'error',
  '@stylistic/no-extra-semi': 'error',
  '@stylistic/no-floating-decimal': 'error',
  '@stylistic/no-multi-spaces': 'error',
  '@stylistic/no-multiple-empty-lines': 'error',
  '@stylistic/no-trailing-spaces': 'error',
  '@stylistic/object-curly-spacing': 'error',
  '@stylistic/quote-props': ['error', 'consistent'],
  '@stylistic/quotes': ['error', 'single', {
    avoidEscape: true,
  }],
  '@stylistic/rest-spread-spacing': 'error',
  '@stylistic/semi': 'error',
  '@stylistic/semi-spacing': 'error',
  '@stylistic/semi-style': 'error',
  '@stylistic/space-before-blocks': 'error',
  '@stylistic/space-before-function-paren': ['error', {
    anonymous: 'always',
    named: 'never',
  }],
  '@stylistic/space-in-parens': 'error',
  '@stylistic/space-infix-ops': 'error',
  '@stylistic/space-unary-ops': 'error',
  '@stylistic/spaced-comment': 'error',
  '@stylistic/yield-star-spacing': 'error',

  'check-file/filename-naming-convention': ['error', {
    '**/*.{js,ts}': 'KEBAB_CASE',
  }, {
    ignoreMiddleExtensions: true,
  }],
  'check-file/folder-naming-convention': ['error', {
    '**/': 'KEBAB_CASE',
  }],
};
